### PR TITLE
Update Asia/Ulaanbaatar

### PR DESCRIPTION
**Pull request by pkoch**

### CODE REVIEW

**Review by fbidu — APPROVED** [review]
your change seems safe enough, @pkoch. The CI error is quite weird, I'll try running it again to see if anything changes.

That said, I find it a bit cumbersome we keeping those timezone lists around and hand-updating them... I think we could achieve the same by applying a set of transformations over the list supplied by `pytz`. It is out of the scope of this issue, but I think it is worth thinking about. Not sure if this has been discussed previously, though.

CC'ing @Schnouki @PotHix

**Comment by fbidu** [comment]
CI error: https://github.com/pypa/setuptools_scm/issues/541

**Comment by fbidu** [comment]
@pkoch can you please try pinning the "setuptools_scm" version? I think this will fix the error here

**Comment by PotHix** [comment]
> Not sure if this has been discussed previously, though.

I don't think it was discussed before. It's worth mentioning that this is an open source project. :)

> I think we could achieve the same by applying a set of transformations over the list supplied by pytz

That would be something to explore 👍

**Comment by fbidu** [comment]
> It's worth mentioning that this is an open source project. :)

Oh! Hi everyone :sweat_smile:

**Comment by pkoch** [comment]
@fbidu to which version should I pin it?

**Comment by fbidu** [comment]
@pkoch things are pretty wild on the issue that is tracking the error... Seems like they are dealing with both a version of SCM error coupled with a 'your-pip-is-too-old' error. Try `setuptools-scm==5.0.2`

**Comment by pkoch** [comment]
Let's take care of that on https://github.com/Doist/python-timezones/pull/17

**Comment by pkoch** [comment]
Gonna cowboy-merge this one, as we're sure enough it's safe. We'll deal with the build issues on the other PR.

**Comment by fbidu** [comment]
> Gonna cowboy-merge this one, as we're sure enough it's safe. We'll deal with the build issues on the other PR.

+1!

**Pull request merged**
